select nazwa,producent,cena from leki WHERE ID =4;
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
insert into leki (nazwa,producent,cena)VALUES("Piramidon","Bayer",80000);
update leki set nazwa="Piramidon", producent="Polfa" where id=6;
delete from leki where id=100;
delete from leki where nazwa="Piramidon";
